cache: apt

language: cpp

compiler:
  - gcc 
  - clang
  
env:
  matrix: 
    - CXX_OLEVEL=0
    - CXX_OLEVEL=3

matrix:
  allow_failures:
    - env: CXX_OLEVEL=0
    - compiler: clang

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL https://raw2.github.com/maverickg/utils/master/shell/wait4.sh
  - chmod 755 ./travis-tool.sh
  - chmod 755 ./wait4.sh
  - ./travis-tool.sh bootstrap
  - more /proc/meminfo
  - free -t -m
  - vmstat
    
install:
  - ./travis-tool.sh install_aptget r-cran-runit ccache
  - ./travis-tool.sh install_r inline Rcpp coda
  - ccache --max-size 8G

before_script: 
  - echo "CXX = ccache `R CMD config CXX`" >> R_Makevars 
  - echo "CXXFLAGS = `R CMD config CXXFLAGS`" >> R_Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i "s/g++/${CXX}${CLANG_EXTRA_ARG}/" R_Makevars
  - sed -i "s/O[0-3]/O$CXX_OLEVEL/" R_Makevars
  - more R_Makevars
  - mkdir -p ~/.R/
  - cat R_Makevars > ~/.R/Makevars
  - more ~/.R/Makevars
  - R -q -e 'library(Rcpp);library(inline);sessionInfo()'

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - R -q -f ./misc/list7.R 

after_script:
  - ccache -s 
